### ISSUE TITLE
Errors installing via PPA or by downloading the DEB file from Launchpad

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri-installer-debian#7]
Errors while trying to use the PPA seem similar on all Ubuntu versions; installing the ``deb`` also triggers errors, but the server is starting anyways afterwards. However importing channels is unsuccessful, not sure if that's the issue on that particular release...

![fullscreen_03_12_17_19_08](https://user-images.githubusercontent.com/1457929/33529050-3bfd0bac-d86b-11e7-87d8-238a7332b53d.png)

#### Ubuntu 16.10
```
osboxes@osboxes:~$ sudo add-apt-repository ppa:learningequality/kolibri
[sudo] password for osboxes: 
 Kolibri is an offline app and platform for universal education.

The latest documentation is available here: http://kolibri.readthedocs.io/

Retrieve and Distribute Open Educational Resources (OER) from online resources or from device to device. Resources are shared as 'channels', amongst which can be found Khan Academy, PhET and CK-12. To find more channels and create your own, please visit our website for sharing and editing channels: http://studio.learningequality.org/

The circumstances of the package are a bit extra-ordinary, given that it's intended for offline environments. So it cannot have any dependencies but aims to provide a portable .deb file.

Adding the PPA as an online source:

  sudo add-apt-repository ppa:learningequality/kolibri
  sudo apt-get update
  sudo apt-get install kolibri

Downloading portable .deb files:

  1. Go to "View package details"
  2. Click on the latest package. It doesn't matter which one, all binaries
     are the same, regardless of your architecture or Ubuntu/Debian version.
  3. Scroll down to "Package files".
  4. Fetch the relevant .deb file.
 More info: https://launchpad.net/~learningequality/+archive/ubuntu/kolibri
Press [ENTER] to continue or ctrl-c to cancel adding it

gpg: keybox '/tmp/tmpdmofrvt0/pubring.gpg' created
gpg: /tmp/tmpdmofrvt0/trustdb.gpg: trustdb created
gpg: key 74F88ADB3194DD81: public key "Launchpad PPA for Foundation for Learning Equality" imported
gpg: Total number processed: 1
gpg:               imported: 1
OK
osboxes@osboxes:~$ sudo apt-get update
Hit:1 http://gb.archive.ubuntu.com/ubuntu yakkety InRelease
Hit:2 http://security.ubuntu.com/ubuntu yakkety-security InRelease  
Ign:3 http://dl.google.com/linux/chrome/deb stable InRelease                   
Ign:4 http://ppa.launchpad.net/learningequality/kolibri/ubuntu yakkety InRelease
Hit:5 http://gb.archive.ubuntu.com/ubuntu yakkety-updates InRelease     
Hit:6 http://dl.google.com/linux/chrome/deb stable Release                     
Hit:7 http://gb.archive.ubuntu.com/ubuntu yakkety-backports InRelease          
Ign:8 http://ppa.launchpad.net/learningequality/kolibri/ubuntu yakkety Release
Ign:9 http://ppa.launchpad.net/learningequality/kolibri/ubuntu yakkety/main i386 Packages
Ign:11 http://ppa.launchpad.net/learningequality/kolibri/ubuntu yakkety/main all Packages
Hit:12 https://download.sublimetext.com apt/stable/ InRelease                
Ign:13 http://ppa.launchpad.net/learningequality/kolibri/ubuntu yakkety/main amd64 Packages
Ign:14 http://ppa.launchpad.net/learningequality/kolibri/ubuntu yakkety/main Translation-en_GB
Ign:15 http://ppa.launchpad.net/learningequality/kolibri/ubuntu yakkety/main Translation-en
Ign:16 http://ppa.launchpad.net/learningequality/kolibri/ubuntu yakkety/main Translation-en_US
Ign:17 http://ppa.launchpad.net/learningequality/kolibri/ubuntu yakkety/main all DEP-11 Metadata
Ign:18 http://ppa.launchpad.net/learningequality/kolibri/ubuntu yakkety/main amd64 DEP-11 Metadata
Ign:19 http://ppa.launchpad.net/learningequality/kolibri/ubuntu yakkety/main DEP-11 64x64 Icons
Ign:9 http://ppa.launchpad.net/learningequality/kolibri/ubuntu yakkety/main i386 Packages
Ign:11 http://ppa.launchpad.net/learningequality/kolibri/ubuntu yakkety/main all Packages
Ign:13 http://ppa.launchpad.net/learningequality/kolibri/ubuntu yakkety/main amd64 Packages
Ign:14 http://ppa.launchpad.net/learningequality/kolibri/ubuntu yakkety/main Translation-en_GB
Ign:15 http://ppa.launchpad.net/learningequality/kolibri/ubuntu yakkety/main Translation-en
Ign:16 http://ppa.launchpad.net/learningequality/kolibri/ubuntu yakkety/main Translation-en_US
Ign:17 http://ppa.launchpad.net/learningequality/kolibri/ubuntu yakkety/main all DEP-11 Metadata
Ign:18 http://ppa.launchpad.net/learningequality/kolibri/ubuntu yakkety/main amd64 DEP-11 Metadata
Ign:19 http://ppa.launchpad.net/learningequality/kolibri/ubuntu yakkety/main DEP-11 64x64 Icons
Ign:9 http://ppa.launchpad.net/learningequality/kolibri/ubuntu yakkety/main i386 Packages
Ign:11 http://ppa.launchpad.net/learningequality/kolibri/ubuntu yakkety/main all Packages
Ign:13 http://ppa.launchpad.net/learningequality/kolibri/ubuntu yakkety/main amd64 Packages
Ign:14 http://ppa.launchpad.net/learningequality/kolibri/ubuntu yakkety/main Translation-en_GB
Ign:15 http://ppa.launchpad.net/learningequality/kolibri/ubuntu yakkety/main Translation-en
Ign:16 http://ppa.launchpad.net/learningequality/kolibri/ubuntu yakkety/main Translation-en_US
Ign:17 http://ppa.launchpad.net/learningequality/kolibri/ubuntu yakkety/main all DEP-11 Metadata
Ign:18 http://ppa.launchpad.net/learningequality/kolibri/ubuntu yakkety/main amd64 DEP-11 Metadata
Ign:19 http://ppa.launchpad.net/learningequality/kolibri/ubuntu yakkety/main DEP-11 64x64 Icons
Ign:9 http://ppa.launchpad.net/learningequality/kolibri/ubuntu yakkety/main i386 Packages
Ign:11 http://ppa.launchpad.net/learningequality/kolibri/ubuntu yakkety/main all Packages
Ign:13 http://ppa.launchpad.net/learningequality/kolibri/ubuntu yakkety/main amd64 Packages
Ign:14 http://ppa.launchpad.net/learningequality/kolibri/ubuntu yakkety/main Translation-en_GB
Ign:15 http://ppa.launchpad.net/learningequality/kolibri/ubuntu yakkety/main Translation-en
Ign:16 http://ppa.launchpad.net/learningequality/kolibri/ubuntu yakkety/main Translation-en_US
Ign:17 http://ppa.launchpad.net/learningequality/kolibri/ubuntu yakkety/main all DEP-11 Metadata
Ign:18 http://ppa.launchpad.net/learningequality/kolibri/ubuntu yakkety/main amd64 DEP-11 Metadata
Ign:19 http://ppa.launchpad.net/learningequality/kolibri/ubuntu yakkety/main DEP-11 64x64 Icons
Ign:9 http://ppa.launchpad.net/learningequality/kolibri/ubuntu yakkety/main i386 Packages
Ign:11 http://ppa.launchpad.net/learningequality/kolibri/ubuntu yakkety/main all Packages
Ign:13 http://ppa.launchpad.net/learningequality/kolibri/ubuntu yakkety/main amd64 Packages
Ign:14 http://ppa.launchpad.net/learningequality/kolibri/ubuntu yakkety/main Translation-en_GB
Ign:15 http://ppa.launchpad.net/learningequality/kolibri/ubuntu yakkety/main Translation-en
Ign:16 http://ppa.launchpad.net/learningequality/kolibri/ubuntu yakkety/main Translation-en_US
Ign:17 http://ppa.launchpad.net/learningequality/kolibri/ubuntu yakkety/main all DEP-11 Metadata
Ign:18 http://ppa.launchpad.net/learningequality/kolibri/ubuntu yakkety/main amd64 DEP-11 Metadata
Ign:19 http://ppa.launchpad.net/learningequality/kolibri/ubuntu yakkety/main DEP-11 64x64 Icons
Err:9 http://ppa.launchpad.net/learningequality/kolibri/ubuntu yakkety/main i386 Packages
  404  Not Found
Ign:11 http://ppa.launchpad.net/learningequality/kolibri/ubuntu yakkety/main all Packages
Ign:13 http://ppa.launchpad.net/learningequality/kolibri/ubuntu yakkety/main amd64 Packages
Ign:14 http://ppa.launchpad.net/learningequality/kolibri/ubuntu yakkety/main Translation-en_GB
Ign:15 http://ppa.launchpad.net/learningequality/kolibri/ubuntu yakkety/main Translation-en
Ign:16 http://ppa.launchpad.net/learningequality/kolibri/ubuntu yakkety/main Translation-en_US
Ign:17 http://ppa.launchpad.net/learningequality/kolibri/ubuntu yakkety/main all DEP-11 Metadata
Ign:18 http://ppa.launchpad.net/learningequality/kolibri/ubuntu yakkety/main amd64 DEP-11 Metadata
Ign:19 http://ppa.launchpad.net/learningequality/kolibri/ubuntu yakkety/main DEP-11 64x64 Icons
Reading package lists... Done
W: The repository 'http://ppa.launchpad.net/learningequality/kolibri/ubuntu yakkety Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://ppa.launchpad.net/learningequality/kolibri/ubuntu/dists/yakkety/main/binary-i386/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
osboxes@osboxes:~$ sudo apt-get install kolibri
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package kolibri
osboxes@osboxes:~$ cd Desktop/
osboxes@osboxes:~/Desktop$ sudo dpkg -i kolibri_0.6.0-0ubuntu1_all.deb 
Selecting previously unselected package kolibri.
(Reading database ... 211505 files and directories currently installed.)
Preparing to unpack kolibri_0.6.0-0ubuntu1_all.deb ...
Unpacking kolibri (0.6.0-0ubuntu1) ...
Setting up kolibri (0.6.0-0ubuntu1) ...
/etc/default/kolibri: line 15: /etc/kolibri/conf.d/*.conf: No such file or directory
Traceback (last called is first):
     source() in /etc/default/kolibri:1
     kolibri_configure() in /var/lib/dpkg/info/kolibri.postinst:121
     main() in /var/lib/dpkg/info/kolibri.postinst:175
dpkg: error processing package kolibri (--install):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for systemd (231-9ubuntu5) ...
Processing triggers for ureadahead (0.100.0-19) ...
Errors were encountered while processing:
 kolibri
osboxes@osboxes:~/Desktop$ 
```

#### Ubuntu 17.04
```
osboxes@osboxes:~$ sudo add-apt-repository ppa:learningequality/kolibri
[sudo] password for osboxes: 
 Kolibri is an offline app and platform for universal education.

The latest documentation is available here: http://kolibri.readthedocs.io/

Retrieve and Distribute Open Educational Resources (OER) from online resources or from device to device. Resources are shared as 'channels', amongst which can be found Khan Academy, PhET and CK-12. To find more channels and create your own, please visit our website for sharing and editing channels: http://studio.learningequality.org/

The circumstances of the package are a bit extra-ordinary, given that it's intended for offline environments. So it cannot have any dependencies but aims to provide a portable .deb file.

Adding the PPA as an online source:

  sudo add-apt-repository ppa:learningequality/kolibri
  sudo apt-get update
  sudo apt-get install kolibri

Downloading portable .deb files:

  1. Go to "View package details"
  2. Click on the latest package. It doesn't matter which one, all binaries
     are the same, regardless of your architecture or Ubuntu/Debian version.
  3. Scroll down to "Package files".
  4. Fetch the relevant .deb file.
 More info: https://launchpad.net/~learningequality/+archive/ubuntu/kolibri
Press [ENTER] to continue or ctrl-c to cancel adding it

gpg: keybox '/tmp/tmpjajzup1g/pubring.gpg' created
gpg: /tmp/tmpjajzup1g/trustdb.gpg: trustdb created
gpg: key 74F88ADB3194DD81: public key "Launchpad PPA for Foundation for Learning Equality" imported
gpg: Total number processed: 1
gpg:               imported: 1
OK
osboxes@osboxes:~$ sudo apt-get update
Hit:1 http://gb.archive.ubuntu.com/ubuntu zesty InRelease
Get:2 http://gb.archive.ubuntu.com/ubuntu zesty-updates InRelease [89.2 kB]    
Get:3 http://ppa.launchpad.net/learningequality/kolibri/ubuntu zesty InRelease [15.9 kB]
Ign:4 http://dl.google.com/linux/chrome/deb stable InRelease                   
Get:5 http://gb.archive.ubuntu.com/ubuntu zesty-backports InRelease [89.2 kB]  
Get:6 http://ppa.launchpad.net/learningequality/kolibri/ubuntu zesty/main amd64 Packages [504 B]
Hit:7 http://dl.google.com/linux/chrome/deb stable Release                     
Get:8 http://ppa.launchpad.net/learningequality/kolibri/ubuntu zesty/main i386 Packages [504 B]
Get:10 http://ppa.launchpad.net/learningequality/kolibri/ubuntu zesty/main Translation-en [416 B]
Get:11 http://security.ubuntu.com/ubuntu zesty-security InRelease [89.2 kB]    
Fetched 285 kB in 2s (99.4 kB/s)                      
Reading package lists... Done
osboxes@osboxes:~$ sudo apt-get install kolibri
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  kolibri
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 40.1 MB of archives.
After this operation, 262 MB of additional disk space will be used.
Get:1 http://ppa.launchpad.net/learningequality/kolibri/ubuntu zesty/main amd64 kolibri all 0.6.0-0ubuntu1 [40.1 MB]
Fetched 40.1 MB in 4min 6s (163 kB/s)                                                                           
Selecting previously unselected package kolibri.
(Reading database ... 213558 files and directories currently installed.)
Preparing to unpack .../kolibri_0.6.0-0ubuntu1_all.deb ...
Unpacking kolibri (0.6.0-0ubuntu1) ...
Processing triggers for ureadahead (0.100.0-19) ...
Processing triggers for systemd (232-21ubuntu7.1) ...
Setting up kolibri (0.6.0-0ubuntu1) ...
/etc/default/kolibri: line 15: /etc/kolibri/conf.d/*.conf: No such file or directory
Traceback (last called is first):
     source() in /etc/default/kolibri:1
     kolibri_configure() in /var/lib/dpkg/info/kolibri.postinst:121
     main() in /var/lib/dpkg/info/kolibri.postinst:175
dpkg: error processing package kolibri (--configure):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for systemd (232-21ubuntu7.1) ...
Processing triggers for ureadahead (0.100.0-19) ...
Errors were encountered while processing:
 kolibri
E: Sub-process /usr/bin/dpkg returned an error code (1)
osboxes@osboxes:~$ cd Desktop/
osboxes@osboxes:~/Desktop$ sudo dpkg -i kolibri_0.6.0-0ubuntu1_all.deb 
(Reading database ... 226304 files and directories currently installed.)
Preparing to unpack kolibri_0.6.0-0ubuntu1_all.deb ...
Unpacking kolibri (0.6.0-0ubuntu1) over (0.6.0-0ubuntu1) ...
Setting up kolibri (0.6.0-0ubuntu1) ...
/etc/default/kolibri: line 15: /etc/kolibri/conf.d/*.conf: No such file or directory
Traceback (last called is first):
     source() in /etc/default/kolibri:1
     kolibri_configure() in /var/lib/dpkg/info/kolibri.postinst:121
     main() in /var/lib/dpkg/info/kolibri.postinst:175
dpkg: error processing package kolibri (--install):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for systemd (232-21ubuntu7.1) ...
Processing triggers for ureadahead (0.100.0-19) ...
Errors were encountered while processing:
 kolibri
osboxes@osboxes:~/Desktop$  
```

On Ubuntu 14.04 I did not manage to install the Python >3.5 requirement, maybe we should exclude this version from the supported OS...? @benjaoming

**Comment by benjaoming** [comment]
Thanks for testing this! Your findings convince me of having a similar set of automated tests as the KA Lite deb package. It's because I haven't been developing on an entirely clean system. Not sure for how long Travis will support `sudo` commands, but the tests can be run locally with the same results.

I will get 0.7 built once 0.6 is stable - so you don't have to worry about the internals for now, unless they are persisting in 0.7 (in this case the channel import stuff)

Have fixed and deployed another release in `ka-lite-proposed`, but Launchpad has a long queue tonight, so I won't be able to finish it before tomorrow.

It's probably best if you re-do the tests on a clean system again since that's my main challenge here :)

**Comment by indirectlylit** [comment]
> I haven't been developing on an entirely clean system ... It's probably best if you re-do the tests on a clean system again since that's my main challenge here

@benjaoming as part of manual testing on your end, I think it's important that you test in a clean ubuntu VM before passing it off to QA

> will get 0.7 built once 0.6 is stable

I think it would be better to focus on 0.7 - there's no need for 0.6 and we need this fully tested and finished Monday.

**Comment by radinamatic** [comment]
Ok @benjaoming, I'll keep an eye on Launchpad, grab the `ka-lite-proposed` as soon as it's ready, and re-test on a fresh VM!

**Comment by benjaoming** [comment]
@indirectlylit 

> @benjaoming as part of manual testing on your end, I think it's important that you test in a clean ubuntu VM before passing it off to QA

Responded elsewhere.

**Comment by benjaoming** [comment]
@radinamatic the PPA has the fix now for the above error, and have changed the Python version to 3.4.

**Comment by radinamatic** [comment]
#### Ubuntu 14.04

@benjaoming Started well, even got to the system service confirmation, but errored out at the end... 

![fullscreen_04_12_17_00_04](https://user-images.githubusercontent.com/1457929/33531025-01e9d3ec-d888-11e7-9bdd-2ef08a866539.png)

Server is starting with `kolibri start`, just no system-service boot, yet... 

![fullscreen_04_12_17_00_11](https://user-images.githubusercontent.com/1457929/33531026-08d46bc2-d888-11e7-9ea3-b9956e8576e1.png)

Upon VM reboot:

![fullscreen_04_12_17_00_19](https://user-images.githubusercontent.com/1457929/33531098-161d9f50-d889-11e7-8e35-dd52ba90acdb.png)


```
osboxes@osboxes:~$ sudo add-apt-repository ppa:learningequality/kolibri-proposed Do not use this PPA in a production environment.

Kolibri is an offline app and platform for universal education.

The latest documentation is available here: http://kolibri.readthedocs.io/

Retrieve and Distribute Open Educational Resources (OER) from online resources or from device to device. Resources are shared as 'channels', amongst which can be found Khan Academy, PhET and CK-12. To find more channels and create your own, please visit our website for sharing and editing channels: http://studio.learningequality.org/

The circumstances of the package are a bit extra-ordinary, given that it's intended for offline environments. So it cannot have any dependencies but aims to provide a portable .deb file.

Adding the PPA as an online source:

  sudo add-apt-repository ppa:learningequality/kolibri
  sudo apt-get update
  sudo apt-get install kolibri

Downloading portable .deb files:

  1. Go to "View package details"
  2. Click on the latest package. It doesn't matter which one, all binaries
     are the same, regardless of your architecture or Ubuntu/Debian version.
  3. Scroll down to "Package files".
  4. Fetch the relevant .deb file.
 More info: https://launchpad.net/~learningequality/+archive/ubuntu/kolibri-proposed
Press [ENTER] to continue or ctrl-c to cancel adding it

gpg: keyring `/tmp/tmpdyhlh0xq/secring.gpg' created
gpg: keyring `/tmp/tmpdyhlh0xq/pubring.gpg' created
gpg: requesting key 3194DD81 from hkp server keyserver.ubuntu.com
gpg: /tmp/tmpdyhlh0xq/trustdb.gpg: trustdb created
gpg: key 3194DD81: public key "Launchpad PPA for Foundation for Learning Equality" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
OK
osboxes@osboxes:~$ sudo apt-get update
Ign http://extras.ubuntu.com trusty InRelease
Ign http://dl.google.com stable InRelease                                      
Hit http://extras.ubuntu.com trusty Release.gpg                                
Hit http://dl.google.com stable Release.gpg                                    
Hit http://extras.ubuntu.com trusty Release                                    
Hit http://dl.google.com stable Release                                        
Hit http://extras.ubuntu.com trusty/main Sources                               
Hit http://dl.google.com stable/main amd64 Packages                            
Hit http://extras.ubuntu.com trusty/main amd64 Packages                        
Get:1 http://ppa.launchpad.net trusty InRelease [16.0 kB]                      
Hit http://extras.ubuntu.com trusty/main i386 Packages                         
Ign http://gb.archive.ubuntu.com trusty InRelease                              
Hit http://gb.archive.ubuntu.com trusty Release.gpg                            
Hit http://ppa.launchpad.net trusty InRelease                                  
Hit http://gb.archive.ubuntu.com trusty Release                                
Hit http://gb.archive.ubuntu.com trusty/main Sources                           
Get:2 http://ppa.launchpad.net trusty/main amd64 Packages [481 B]              
Hit http://gb.archive.ubuntu.com trusty/restricted Sources                     
Hit http://gb.archive.ubuntu.com trusty/universe Sources                       
Hit http://gb.archive.ubuntu.com trusty/multiverse Sources                     
Get:3 http://ppa.launchpad.net trusty/main i386 Packages [481 B]               
Hit http://gb.archive.ubuntu.com trusty/main amd64 Packages                    
Hit http://gb.archive.ubuntu.com trusty/restricted amd64 Packages              
Hit http://gb.archive.ubuntu.com trusty/universe amd64 Packages                
Hit http://gb.archive.ubuntu.com trusty/multiverse amd64 Packages              
Hit http://gb.archive.ubuntu.com trusty/main i386 Packages                     
Get:4 http://ppa.launchpad.net trusty/main Translation-en [381 B]              
Hit http://gb.archive.ubuntu.com trusty/restricted i386 Packages               
Ign http://extras.ubuntu.com trusty/main Translation-en_US                     
Hit http://gb.archive.ubuntu.com trusty/universe i386 Packages                 
Ign http://extras.ubuntu.com trusty/main Translation-en                        
Ign http://dl.google.com stable/main Translation-en_US                         
Hit http://ppa.launchpad.net trusty/main amd64 Packages                        
Hit http://gb.archive.ubuntu.com trusty/multiverse i386 Packages               
Ign http://extras.ubuntu.com trusty/main Translation-en_GB                     
Ign http://dl.google.com stable/main Translation-en                            
Hit http://gb.archive.ubuntu.com trusty/main Translation-en                    
Ign http://dl.google.com stable/main Translation-en_GB                         
Hit http://gb.archive.ubuntu.com trusty/main Translation-en_GB                 
Hit http://ppa.launchpad.net trusty/main i386 Packages                         
Hit http://gb.archive.ubuntu.com trusty/multiverse Translation-en              
Hit http://gb.archive.ubuntu.com trusty/multiverse Translation-en_GB           
Hit http://gb.archive.ubuntu.com trusty/restricted Translation-en              
Hit http://gb.archive.ubuntu.com trusty/restricted Translation-en_GB           
Hit http://gb.archive.ubuntu.com trusty/universe Translation-en                
Hit http://gb.archive.ubuntu.com trusty/universe Translation-en_GB 
Ign http://gb.archive.ubuntu.com trusty/main Translation-en_US              
Ign http://gb.archive.ubuntu.com trusty/multiverse Translation-en_US
Ign http://gb.archive.ubuntu.com trusty/restricted Translation-en_US
Ign http://gb.archive.ubuntu.com trusty/universe Translation-en_US
Hit http://ppa.launchpad.net trusty/main Translation-en                        
Fetched 17.3 kB in 23s (752 B/s)
Reading package lists... Done
osboxes@osboxes:~$ sudo apt-get install kolibri
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  linux-headers-4.4.0-31 linux-headers-4.4.0-31-generic
  linux-image-4.4.0-31-generic linux-image-extra-4.4.0-31-generic
Use 'apt-get autoremove' to remove them.
Suggested packages:
  python3-cryptography
The following NEW packages will be installed:
  kolibri
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 41.6 MB of archives.
After this operation, 262 MB of additional disk space will be used.
Get:1 http://ppa.launchpad.net/learningequality/kolibri-proposed/ubuntu/ trusty/main kolibri all 0.6.0-0ubuntu3 [41.6 MB]
Fetched 41.6 MB in 2min 41s (258 kB/s)                                         
Preconfiguring packages ...
Selecting previously unselected package kolibri.
(Reading database ... 251321 files and directories currently installed.)
Preparing to unpack .../kolibri_0.6.0-0ubuntu3_all.deb ...
Unpacking kolibri (0.6.0-0ubuntu3) ...
Processing triggers for ureadahead (0.100.0-16) ...
ureadahead will be reprofiled on next reboot
Setting up kolibri (0.6.0-0ubuntu3) ...
Creating new user kolibri
Adding system user `kolibri' (UID 116) ...
Adding new user `kolibri' (UID 116) with group `nogroup' ...
Creating home directory `/var/kolibri' ...
 Removing any system startup links for /etc/init.d/kolibri ...
 Adding system startup for /etc/init.d/kolibri ...
   /etc/rc0.d/K20kolibri -> ../init.d/kolibri
   /etc/rc1.d/K20kolibri -> ../init.d/kolibri
   /etc/rc6.d/K20kolibri -> ../init.d/kolibri
   /etc/rc2.d/S20kolibri -> ../init.d/kolibri
   /etc/rc3.d/S20kolibri -> ../init.d/kolibri
   /etc/rc4.d/S20kolibri -> ../init.d/kolibri
   /etc/rc5.d/S20kolibri -> ../init.d/kolibri
Traceback (most recent call last):
  File "/usr/bin/kolibri", line 9, in <module>
    load_entry_point('kolibri==0.6.0', 'console_scripts', 'kolibri')()
  File "/usr/lib/python3/dist-packages/kolibri/utils/cli.py", line 620, in main
    initialize(debug=debug)
  File "/usr/lib/python3/dist-packages/kolibri/utils/cli.py", line 178, in initialize
    django.setup()
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/__init__.py", line 17, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/conf/__init__.py", line 55, in __getattr__
    self._setup(name)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/conf/__init__.py", line 43, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/conf/__init__.py", line 99, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/kolibri/deployment/default/settings/base.py", line 20, in <module>
    from kolibri.utils import conf, i18n
  File "/usr/lib/python3/dist-packages/kolibri/utils/conf.py", line 37, in <module>
    os.mkdir(KOLIBRI_HOME)
PermissionError: [Errno 13] Permission denied: '/home/osboxes/.kolibri'
invoke-rc.d: initscript kolibri, action "start" failed.
Processing triggers for ureadahead (0.100.0-16) ...
osboxes@osboxes:~$ 
```

**Comment by benjaoming** [comment]
@radinamatic this is quite strange, seems that `KOLIBRI_HOME` is pointing to the home directory of your logged in user `osboxes`, and not `/var/kolibri`, which the system service should be using.

It's quite exotic since the environment that the system service is running should explicitly NOT be affected by your login shell.

I'm going to investigate for 14.04 if this is deviation. Are you seeing the same on 16.04?

**Comment by radinamatic** [comment]
@benjaoming Must be a 14.04 issue as on 16.04 everything goes smooth, system-service is installed without errors, and kolibri is running on VM reboot>

![fullscreen_04_12_17_02_38](https://user-images.githubusercontent.com/1457929/33532721-5c10738a-d89c-11e7-826b-9e1eaadaeb58.png)


```
osboxes@osboxes:~$ sudo add-apt-repository ppa:learningequality/kolibri-proposed
[sudo] password for osboxes: 
 Do not use this PPA in a production environment.

Kolibri is an offline app and platform for universal education.

The latest documentation is available here: http://kolibri.readthedocs.io/

Retrieve and Distribute Open Educational Resources (OER) from online resources or from device to device. Resources are shared as 'channels', amongst which can be found Khan Academy, PhET and CK-12. To find more channels and create your own, please visit our website for sharing and editing channels: http://studio.learningequality.org/

The circumstances of the package are a bit extra-ordinary, given that it's intended for offline environments. So it cannot have any dependencies but aims to provide a portable .deb file.

Adding the PPA as an online source:

  sudo add-apt-repository ppa:learningequality/kolibri
  sudo apt-get update
  sudo apt-get install kolibri

Downloading portable .deb files:

  1. Go to "View package details"
  2. Click on the latest package. It doesn't matter which one, all binaries
     are the same, regardless of your architecture or Ubuntu/Debian version.
  3. Scroll down to "Package files".
  4. Fetch the relevant .deb file.
 More info: https://launchpad.net/~learningequality/+archive/ubuntu/kolibri-proposed
Press [ENTER] to continue or ctrl-c to cancel adding it

gpg: keyring `/tmp/tmph7g7qzny/secring.gpg' created
gpg: keyring `/tmp/tmph7g7qzny/pubring.gpg' created
gpg: requesting key 3194DD81 from hkp server keyserver.ubuntu.com
gpg: /tmp/tmph7g7qzny/trustdb.gpg: trustdb created
gpg: key 3194DD81: public key "Launchpad PPA for Foundation for Learning Equality" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
OK
osboxes@osboxes:~$ sudo apt-get update
Ign:1 http://dl.google.com/linux/chrome/deb stable InRelease
Hit:2 http://gb.archive.ubuntu.com/ubuntu xenial InRelease                                       
Get:3 http://ppa.launchpad.net/learningequality/kolibri-proposed/ubuntu xenial InRelease [18.1 kB]     
Hit:4 http://dl.google.com/linux/chrome/deb stable Release                                             
Get:5 http://gb.archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]                            
Get:7 http://gb.archive.ubuntu.com/ubuntu xenial-backports InRelease [102 kB]                          
Get:8 http://ppa.launchpad.net/learningequality/kolibri-proposed/ubuntu xenial/main amd64 Packages [512 B]
Get:9 http://ppa.launchpad.net/learningequality/kolibri-proposed/ubuntu xenial/main i386 Packages [512 B]
Get:10 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]                           
Get:11 http://ppa.launchpad.net/learningequality/kolibri-proposed/ubuntu xenial/main Translation-en [416 B]
Fetched 326 kB in 2s (155 kB/s)                                          
Reading package lists... Done
osboxes@osboxes:~$ sudo apt-get update
Ign:1 http://dl.google.com/linux/chrome/deb stable InRelease
Hit:2 http://ppa.launchpad.net/learningequality/kolibri-proposed/ubuntu xenial InRelease
Hit:3 http://gb.archive.ubuntu.com/ubuntu xenial InRelease          
Hit:4 http://dl.google.com/linux/chrome/deb stable Release                                     
Get:5 http://gb.archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]                    
Get:6 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]         
Get:8 http://gb.archive.ubuntu.com/ubuntu xenial-backports InRelease [102 kB]                  
Fetched 306 kB in 1s (288 kB/s)                                                            
Reading package lists... Done
osboxes@osboxes:~$ sudo apt-get install kolibri
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  kolibri
0 upgraded, 1 newly installed, 0 to remove and 9 not upgraded.
Need to get 41.6 MB of archives.
After this operation, 262 MB of additional disk space will be used.
Get:1 http://ppa.launchpad.net/learningequality/kolibri-proposed/ubuntu xenial/main amd64 kolibri all 0.6.0-0ubuntu3 [41.6 MB]
Fetched 41.6 MB in 2min 47s (248 kB/s)                                                                                        
Preconfiguring packages ...
Selecting previously unselected package kolibri.
(Reading database ... 246369 files and directories currently installed.)
Preparing to unpack .../kolibri_0.6.0-0ubuntu3_all.deb ...
Unpacking kolibri (0.6.0-0ubuntu3) ...
Processing triggers for systemd (229-4ubuntu21) ...
Processing triggers for ureadahead (0.100.0-19) ...
Setting up kolibri (0.6.0-0ubuntu3) ...
Creating new user kolibri
Adding system user `kolibri' (UID 121) ...
Adding new user `kolibri' (UID 121) with group `nogroup' ...
Creating home directory `/var/kolibri' ...
Synchronizing state of kolibri.service with SysV init with /lib/systemd/systemd-sysv-install...
Executing /lib/systemd/systemd-sysv-install enable kolibri
Processing triggers for systemd (229-4ubuntu21) ...
Processing triggers for ureadahead (0.100.0-19) ...
osboxes@osboxes:~$
```

**Comment by benjaoming** [comment]
Thanks for testing this @radinamatic ! Will track in a separate issue. Have removed Trusty support for now and will delete already released Trusty packages.
